/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Business;
import static Business.Business.business;
import Business.ConfigureBusiness;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Interface.Customer.*;
import Interface.Supplier.*;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ajaygoel
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Business business;
    public MainJFrame() {
        initComponents();
                JPanel blankJPanel = new JPanel();
        JLabel imageLabel =new JLabel();
        String imageTxt= "src/Pics/virtual-mall-1225652699373047-8-101002102056-phpapp01-thumbnail-4.jpg";
        
                try {
            BufferedImage img = ImageIO.read(new File(imageTxt));

           imageLabel.setBounds(100, 100, 900, 900);

            Image dimg = img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(dimg);

            imageLabel.setIcon(icon);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
          
          blankJPanel.add(imageLabel);
          userProcessContainer.add("blankJPanel",blankJPanel);
        business = ConfigureBusiness.initializeBusiness();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanel = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userNameTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PasswordTxtField = new javax.swing.JTextField();
        LoginBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        signUpJBtn = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPanel.setDividerLocation(250);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setText("UserName:");

        jLabel2.setText("Password:");

        LoginBtn.setText("Log In>>");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        LogOutBtn.setText("<< Log Out ");
        LogOutBtn.setEnabled(false);
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Welcome, Login:");

        signUpJBtn.setText("Sign up Customer");
        signUpJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(PasswordTxtField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userNameTxtField))
                    .addComponent(LoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(signUpJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(userNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(PasswordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOutBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpJBtn)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        SplitPanel.setLeftComponent(jPanel1);

        userProcessContainer.setPreferredSize(new java.awt.Dimension(400, 400));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        SplitPanel.setRightComponent(userProcessContainer);

        getContentPane().add(SplitPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        String User_name = userNameTxtField.getText().trim();
        String Password = PasswordTxtField.getText().trim();
        boolean flag = false;

        for(UserAccount ua : business.getUserAccountDirectory().getUserAccountDirectory())
        {
            if(ua.getUserName().equals(User_name)&& ua.getPassword().equals(Password))
            {
                userProcessContainer.removeAll();
                if(ua.getRole().equals(UserAccount.ADMIN_ROLE)){
                    AdminWorkAreaJPanel awjpanel = new AdminWorkAreaJPanel(userProcessContainer, business);
                    userProcessContainer.add("AdminWorkAreaJPanel",awjpanel);
                    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                    flag =true;
                    break;

                }
                else if(ua.getRole().equals(UserAccount.SUPPLIER_ROLE)){
                    SupplierWorkAreaJPanel panel = new SupplierWorkAreaJPanel(userProcessContainer,business,ua);
                    userProcessContainer.add("SupplierWorkAreaJPanel",panel);
                    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                    flag =true;
                    break;

                }
                
                else if(ua.getRole().equals(UserAccount.CUSTOMER_ROLE)){
                    Interface.Customer.CustomerWorkAreaJPanel iccwajp= new Interface.Customer.CustomerWorkAreaJPanel(userProcessContainer,business,ua);
                    userProcessContainer.add("Interface.Customer.CustomerWorkAreaJPanel",iccwajp);
                    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                    flag =true;
                    break;
                }
                

            }
        }
        if(flag == false){
            JOptionPane.showMessageDialog(this, "Invalid UserName and Password","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

        userNameTxtField.setEnabled(false);
        PasswordTxtField.setEnabled(false);
        LoginBtn.setEnabled(false);
        LogOutBtn.setEnabled(true);
         signUpJBtn.setEnabled(false);
        

    }//GEN-LAST:event_LoginBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        // TODO add your handling code here:
        userNameTxtField.setEnabled(true);
        PasswordTxtField.setEnabled(true);
        LoginBtn.setEnabled(true);
        signUpJBtn.setEnabled(true);
        LogOutBtn.setEnabled(false);
        userNameTxtField.setText("");
        PasswordTxtField.setText("");
        userProcessContainer.removeAll();

        JPanel blankJPanel = new JPanel();
        JLabel imageLabel = new JLabel();
        String imageTxt= "src/Pics/virtual-mall-1225652699373047-8-101002102056-phpapp01-thumbnail-4.jpg";

        try {
            BufferedImage img = ImageIO.read(new File(imageTxt));

            imageLabel.setBounds(100, 100, 900, 900);

            Image dimg = img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(dimg);

            imageLabel.setIcon(icon);
        } catch (IOException e) {
            e.printStackTrace();
        }

        blankJPanel.add(imageLabel);
        userProcessContainer.add("blankJPanel", blankJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void signUpJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpJBtnActionPerformed
        // TODO add your handling code here:
        
        Interface.Customer.CustomerLoginJFrame iccwajp = new Interface.Customer.CustomerLoginJFrame(userProcessContainer,business);
        userProcessContainer.add("Interface.Customer.CustomerLoginJFrame",iccwajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_signUpJBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JTextField PasswordTxtField;
    private javax.swing.JSplitPane SplitPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton signUpJBtn;
    private javax.swing.JTextField userNameTxtField;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
