/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Supplier;

import Business.Business;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ajaygoel
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierWorkAreaJPanel
     */

    private JPanel userProcessContainer;
    private Business business;
    private UserAccount ua;
    private Supplier sup;
    public SupplierWorkAreaJPanel(JPanel userProcessContainer, Business business, UserAccount ua) {
        initComponents();
        this.business = business;
        this.userProcessContainer=userProcessContainer;
        this.ua = ua;
        System.out.println(ua+" hi");
        
        for(Supplier s: business.getSupplierDirectory().getSupplierDirectory())
        {
            System.out.println(s.getUserAccount()+" hello");
            System.out.println(ua+" hi");
          
                if(s.getUserAccount().equals(ua))
                {
                    sup =s;
                }
            
            
        }
            
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageProducts = new javax.swing.JButton();
        ManageAccountsBtn = new javax.swing.JButton();
        ManageSupAccountsJPanel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Supplier Work Area");

        manageProducts.setText("Manage Products");
        manageProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductsActionPerformed(evt);
            }
        });

        ManageAccountsBtn.setText("Manage Orders");
        ManageAccountsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAccountsBtnActionPerformed(evt);
            }
        });

        ManageSupAccountsJPanel.setText("Manage Accounts");
        ManageSupAccountsJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSupAccountsJPanelActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/images123.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(ManageAccountsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(ManageSupAccountsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(manageProducts)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ManageAccountsBtn)
                        .addGap(18, 18, 18)
                        .addComponent(ManageSupAccountsJPanel))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductsActionPerformed
        // TODO add your handling code here:
        Interface.Supplier.ManageProductCatalogJPanel ismpcjp = new Interface.Supplier.ManageProductCatalogJPanel(userProcessContainer,business,sup);
        userProcessContainer.add("Interface.Supplier.ManageProductCatalogJPanel",ismpcjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProductsActionPerformed

    private void ManageAccountsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAccountsBtnActionPerformed
        // TODO add your handling code here:
        ManageOrdersJPanel ismpcjp = new ManageOrdersJPanel(userProcessContainer,business,sup);
        userProcessContainer.add("ManageOrdersJPanel",ismpcjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_ManageAccountsBtnActionPerformed

    private void ManageSupAccountsJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSupAccountsJPanelActionPerformed
        // TODO add your handling code here:

        Interface.Supplier.UpdateSupplierAccountsJPanel isusajp = new Interface.Supplier.UpdateSupplierAccountsJPanel(userProcessContainer,business,sup,ua);
        userProcessContainer.add("Interface.Supplier.UpdateSupplierAccountsJPanel",isusajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageSupAccountsJPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageAccountsBtn;
    private javax.swing.JButton ManageSupAccountsJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageProducts;
    // End of variables declaration//GEN-END:variables
}
