/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import Business.Business;
import Business.Customer.Customer;
import Business.Order.OrderItem;
import Business.Product.Product;
import Business.Supplier.Supplier;
import java.awt.CardLayout;
import java.util.Map.Entry;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankit
 */
public class SupplierDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierDetailsJPanel
     */
    public SupplierDetailsJPanel() {
    }
    
    private JPanel userProcessContainer;
    private Business business;
    private Supplier s;

    SupplierDetailsJPanel(JPanel userProcessContainer, Business business, Supplier s) {
                initComponents();
                this.userProcessContainer=userProcessContainer;
                this.s=s;
                this.business=business;
                
                suppNameTxtField.setText(s.getSupplier_name());
                suppNameTxtField.setEnabled(false);
                updateJBtn.setEnabled(true);
                saveJBtn.setEnabled(false);
                
                populateProductTable();
                PopulateOrderTable();

    }
    
    public void populateProductTable(){
        
        DefaultTableModel dtm = (DefaultTableModel) prodListJTbl.getModel();
        dtm.setRowCount(0);
        
        for(Product p: s.getProductDirectory().getProductDirectory()){
            Object row[]= new Object[4];
            row[0]= p;
            row[1] = p.getModelNumber();
            row[2] = p.getPrice();
            row[3]= p.getAvail();
            dtm.addRow(row);
            
        }
        
    }
    
    public void PopulateOrderTable() {

        DefaultTableModel dtm = (DefaultTableModel) orderListJTbl.getModel();
        dtm.setRowCount(0);

        for (Entry<OrderItem, Customer> e : s.getSuppOrderList().entrySet()) {
            OrderItem oi = e.getKey();
            Customer c = e.getValue();
            Object row[] = new Object[5];
            row[0] = c.getFirstName() + " " + c.getLastName();
            row[1] = oi.getProduct();
            row[2] = oi.getQuantity();
            row[3] = oi.getSalesPrice();
            row[4] = oi.getOrderStatus();
            dtm.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        suppNameTxtField = new javax.swing.JTextField();
        updateJBtn = new javax.swing.JButton();
        saveJBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodListJTbl = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderListJTbl = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Supplier Details");

        jLabel2.setText("Supplier Name: ");

        updateJBtn.setText("Update");
        updateJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJBtnActionPerformed(evt);
            }
        });

        saveJBtn.setText("Save");
        saveJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Product List");

        prodListJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Model Number", "Price", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(prodListJTbl);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Order List");

        orderListJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Detail", "Product Name", "Order Quantity", "Order Price", "Order Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderListJTbl);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(suppNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateJBtn)
                        .addGap(18, 18, 18)
                        .addComponent(saveJBtn))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(backBtn))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(suppNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateJBtn)
                    .addComponent(saveJBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJBtnActionPerformed
        // TODO add your handling code here:
        updateJBtn.setEnabled(false);
        suppNameTxtField.setEnabled(true);
        saveJBtn.setEnabled(true);
        
        
       
    }//GEN-LAST:event_updateJBtnActionPerformed

    private void saveJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJBtnActionPerformed
        // TODO add your handling code here:
        
        String suppName= suppNameTxtField.getText();
        
        if(suppName.equals("")){
            
             JOptionPane.showMessageDialog(this, "Supplier name can not be blank","Error",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            s.setSupplier_name(suppName);
             JOptionPane.showMessageDialog(this, "Supplier name updated successfully","Success",JOptionPane.INFORMATION_MESSAGE);
             suppNameTxtField.setText(s.getSupplier_name());
                suppNameTxtField.setEnabled(false);
                updateJBtn.setEnabled(true);
                saveJBtn.setEnabled(false);
        }
    }//GEN-LAST:event_saveJBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
   
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderListJTbl;
    private javax.swing.JTable prodListJTbl;
    private javax.swing.JButton saveJBtn;
    private javax.swing.JTextField suppNameTxtField;
    private javax.swing.JButton updateJBtn;
    // End of variables declaration//GEN-END:variables
}
