/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarList;
import business.ExcelRead;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFCell;

/**
 *
 * @author ankit
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    CarList cc;
    public CreateJPanel(CarList cc) {
        initComponents();
        this.cc=cc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avalButtonGroup = new javax.swing.ButtonGroup();
        manCertButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        selectFileBtn = new javax.swing.JButton();
        uploadFileTxtField = new javax.swing.JTextField();
        manTxtField = new javax.swing.JTextField();
        serNumTxtField = new javax.swing.JTextField();
        modTxtField = new javax.swing.JTextField();
        manYearTxtField = new javax.swing.JTextField();
        noOfSeatsTxtField = new javax.swing.JTextField();
        cityTxtField = new javax.swing.JTextField();
        uploadJButton = new javax.swing.JButton();
        yesRadioBtn = new javax.swing.JRadioButton();
        noRadioBtn = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create Car Catalogue");

        jLabel2.setText("ManuFacturer");

        jLabel3.setText("Serial Number");

        jLabel4.setText("Model Number");

        jLabel5.setText("Manufacturer Year");

        jLabel6.setText("No Of Seats");

        jLabel7.setText("City");

        jLabel8.setText("Available");

        jLabel9.setText("Manufacturing Certificate");

        createBtn.setText("Create Catalogue");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        selectFileBtn.setText("Select File");
        selectFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileBtnActionPerformed(evt);
            }
        });

        manTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manTxtFieldActionPerformed(evt);
            }
        });

        uploadJButton.setText("Upload");
        uploadJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadJButtonActionPerformed(evt);
            }
        });

        avalButtonGroup.add(yesRadioBtn);
        yesRadioBtn.setSelected(true);
        yesRadioBtn.setText("Yes");

        avalButtonGroup.add(noRadioBtn);
        noRadioBtn.setText("No");

        manCertButtonGroup.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Valid");

        manCertButtonGroup.add(jRadioButton2);
        jRadioButton2.setText("Expired");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cityTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noOfSeatsTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manYearTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serNumTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yesRadioBtn)
                                    .addComponent(jRadioButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(noRadioBtn))
                                .addGap(5, 5, 5)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uploadFileTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(uploadJButton)))
                        .addGap(18, 18, 18)
                        .addComponent(selectFileBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(createBtn)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(manTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadFileTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFileBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(serNumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(uploadJButton)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manYearTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(noOfSeatsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(yesRadioBtn)
                    .addComponent(noRadioBtn))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(47, 47, 47)
                .addComponent(createBtn)
                .addContainerGap(281, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manTxtFieldActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        
    
    int countError=0;
    
       if(cityTxtField.getText().equals("")||modTxtField.getText().equals("")||manTxtField.getText().equals("")||serNumTxtField.getText().equals("")
               ||manYearTxtField.getText().equals("")||noOfSeatsTxtField.getText().equals(""))
       {
             JOptionPane.showMessageDialog(null, "None of the fields can be blank" ); 
             countError++; 
       }
       else{
    String manufacturer= manTxtField.getText();
    int manYear=0,noOfSeats=0 ;
    try{
    manYear= Integer.parseInt(manYearTxtField.getText());
    
    }catch(NumberFormatException E){
       JOptionPane.showMessageDialog(null, "Please enter a numeric value for Manufacturing Year." ); 
       countError++;
    }
    String serialNum= serNumTxtField.getText();
    try{
    noOfSeats = Integer.parseInt(noOfSeatsTxtField.getText());
    }catch(NumberFormatException E){
        JOptionPane.showMessageDialog(null, "Number of Seats should be between numeric and can't be blank." ); 
        countError++;

    }
    String modelNumber= modTxtField.getText();
    String city= cityTxtField.getText();
    String mainCert= null;
    String isAval = null;
    
              for (Enumeration<AbstractButton> buttons = avalButtonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                isAval= button.getText();
            }
            
        }
    
    Boolean isAvailable=false;
    if(isAval.equalsIgnoreCase("YES"))isAvailable=true;// manCertButtonGroup
    
    
    
     for (Enumeration<AbstractButton> buttons = manCertButtonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                mainCert= button.getText();
            }
            
        }
    
    
    
    
 
    
    if(countError==0){
    Car c= cc.addCar();
    c.setCity(city);
    c.setIsAvailable(isAvailable);
    c.setMainCert(mainCert);
    c.setManYear(manYear);
    c.setManufacturer(manufacturer);
    c.setModelNumber(modelNumber);
    c.setNoOfSeats(noOfSeats);
    c.setSerialNum(serialNum);
    String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date());
    
    cc.setUpdateTime(timeStamp);
    
    
    JOptionPane.showMessageDialog(null, "Car details SUCCESSFULLY saved !!!" );
    
    manTxtField.setText("");
    manYearTxtField.setText("");
    serNumTxtField.setText("");
    noOfSeatsTxtField.setText("");
    modTxtField.setText("");
    cityTxtField.setText("");
    
    
    }
    
       }
    
     
    }//GEN-LAST:event_createBtnActionPerformed

    private void uploadJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadJButtonActionPerformed
        // TODO add your handling code here:
        
        String fileName= uploadFileTxtField.getText();
        
      //  System.out.println(fileName);
        if(fileName.equals("")){
            JOptionPane.showMessageDialog(null, "Please select a file first and then click on upload" );
        }
        
        else if(!fileName.endsWith(".xls")){
            JOptionPane.showMessageDialog(null, "Please select a XLS file with correct data" );
        }
        else{
        
        //  cc.uploadFromXls(fileName);
        ExcelRead es= new ExcelRead();
        
        List<List<HSSFCell>> list=null;
        try {
            list = es.mainRead(fileName);
        } catch (Exception ex) {
            Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      //  Car c= cc.addCar();
        
        for(List<HSSFCell> cell: list){
                Car c= cc.addCar();
                c.setManufacturer(cell.get(0).getRichStringCellValue().getString());
                
                int manYear=(int)(cell.get(1).getNumericCellValue());
               // System.out.println("ManYear "+manYear);
                c.setManYear(manYear);
                        
                String serNum=(cell.get(2).getRichStringCellValue().getString());
                c.setSerialNum(serNum);
                        
                int noOfSeats=(int)(cell.get(3).getNumericCellValue());
                c.setNoOfSeats(noOfSeats);
                
                c.setModelNumber(cell.get(4).getRichStringCellValue().getString());
                c.setCity(cell.get(5).getRichStringCellValue().getString());
                c.setMainCert(cell.get(6).getRichStringCellValue().getString());
                
                String isAval=(cell.get(7).getRichStringCellValue().getString());
                Boolean isAvailable=false;
                if(isAval.equalsIgnoreCase("YES"))isAvailable=true;
                c.setIsAvailable(isAvailable);
                
               
                
                
                
            
        }
        
           String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date());
    
           cc.setUpdateTime(timeStamp);
                 
          JOptionPane.showMessageDialog(null, "Car details SUCCESSFULLY saved !!!" );
        }
    }//GEN-LAST:event_uploadJButtonActionPerformed

    private void selectFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileBtnActionPerformed
        // TODO add your handling code here:
        
         JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        String fileName= f.getAbsolutePath();
        uploadFileTxtField.setText(fileName);
    }//GEN-LAST:event_selectFileBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup avalButtonGroup;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.ButtonGroup manCertButtonGroup;
    private javax.swing.JTextField manTxtField;
    private javax.swing.JTextField manYearTxtField;
    private javax.swing.JTextField modTxtField;
    private javax.swing.JTextField noOfSeatsTxtField;
    private javax.swing.JRadioButton noRadioBtn;
    private javax.swing.JButton selectFileBtn;
    private javax.swing.JTextField serNumTxtField;
    private javax.swing.JTextField uploadFileTxtField;
    private javax.swing.JButton uploadJButton;
    private javax.swing.JRadioButton yesRadioBtn;
    // End of variables declaration//GEN-END:variables
}
