/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarList;
import java.awt.BorderLayout;
import java.util.Enumeration;
import java.util.ListIterator;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ankit
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    CarList cc;
    
    public SearchJPanel(CarList cc) {
        initComponents();
        this.cc=cc;
        
        numOfCarsJTextField.setText(String.valueOf(cc.getCarCatalogue().size()));
        avalCarsNumJTextField.setText(String.valueOf(cc.noOfAvailableCars()));
        updatedDateTextField.setText(cc.getUpdateTime());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchButtonGroup = new javax.swing.ButtonGroup();
        firstAvalJBtn = new javax.swing.JButton();
        searchTxtField = new javax.swing.JTextField();
        ManufacturerJRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        manYearJRadioButton = new javax.swing.JRadioButton();
        showAvalToggleBtn = new javax.swing.JToggleButton();
        modNumJRadioButton = new javax.swing.JRadioButton();
        cityJRadioButton = new javax.swing.JRadioButton();
        expMainCertJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        numOfCarsJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        avalCarsNumJTextField = new javax.swing.JTextField();
        searchFinalJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ourCarManJButton = new javax.swing.JButton();
        avaWithSeatsJBtn = new javax.swing.JButton();
        initialSeatTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        finalSeatTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        updatedDateTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        firstAvalJBtn.setText("First Available Car");
        firstAvalJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstAvalJBtnActionPerformed(evt);
            }
        });

        searchButtonGroup.add(ManufacturerJRadioButton);
        ManufacturerJRadioButton.setSelected(true);
        ManufacturerJRadioButton.setText("Manufacturer");
        ManufacturerJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManufacturerJRadioButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Search By: ");

        searchButtonGroup.add(manYearJRadioButton);
        manYearJRadioButton.setText("Manufacturing Year");

        showAvalToggleBtn.setText("Show Available only");
        showAvalToggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAvalToggleBtnActionPerformed(evt);
            }
        });

        searchButtonGroup.add(modNumJRadioButton);
        modNumJRadioButton.setText("Model Number");

        searchButtonGroup.add(cityJRadioButton);
        cityJRadioButton.setText("City");

        expMainCertJButton.setText("Cars with Expired Maintenance Certificate");
        expMainCertJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expMainCertJButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Total Cars:");

        numOfCarsJTextField.setEditable(false);
        numOfCarsJTextField.setEnabled(false);
        numOfCarsJTextField.setOpaque(false);

        jLabel5.setText("Toatal Available Cars: ");

        avalCarsNumJTextField.setEditable(false);
        avalCarsNumJTextField.setEnabled(false);
        avalCarsNumJTextField.setOpaque(false);

        searchFinalJButton.setText("Search");
        searchFinalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFinalJButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Get Available Cars: ");

        ourCarManJButton.setText("Our Car Manufacturers");
        ourCarManJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ourCarManJButtonActionPerformed(evt);
            }
        });

        avaWithSeatsJBtn.setText("Available with seats between");
        avaWithSeatsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaWithSeatsJBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("and");

        jLabel8.setText("Last Updated On: ");

        updatedDateTextField.setEditable(false);
        updatedDateTextField.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Search Our Catalog");

        searchButtonGroup.add(jRadioButton1);
        jRadioButton1.setText("Serial Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ManufacturerJRadioButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstAvalJBtn)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(avaWithSeatsJBtn)
                                            .addGap(18, 18, 18)
                                            .addComponent(initialSeatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(finalSeatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(searchFinalJButton)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(avalCarsNumJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(showAvalToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityJRadioButton)
                            .addComponent(manYearJRadioButton)
                            .addComponent(jLabel2)
                            .addComponent(ourCarManJButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(numOfCarsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(expMainCertJButton, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updatedDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(modNumJRadioButton)
                            .addComponent(jRadioButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel9)))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addComponent(ourCarManJButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numOfCarsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(avalCarsNumJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstAvalJBtn)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avaWithSeatsJBtn)
                    .addComponent(initialSeatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(finalSeatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchFinalJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManufacturerJRadioButton)
                    .addComponent(showAvalToggleBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manYearJRadioButton)
                .addGap(8, 8, 8)
                .addComponent(modNumJRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cityJRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(expMainCertJButton)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(updatedDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstAvalJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstAvalJBtnActionPerformed
        // TODO add your handling code here:
        
        cc.flushSearchCatalog();
        Car firstAvail=null;
        
    //    firstAvail= cc.getFirstAvail();
        
            for(Car c: cc.getCarCatalogue()){
            if(c.getIsAvailable()){
                firstAvail=c;
                break;
            }
        }
    
        
        if(firstAvail==null){
             JOptionPane.showMessageDialog(null, "Sorry! No cars are available at this time.");
        }
        else{
        cc.addCarToSearch(firstAvail);
        
        }
        

        
        ViewSearchJPanelFinal vp= new ViewSearchJPanelFinal(cc);
        
       //  newPanel obj = new newPanel ();
          setLayout(new BorderLayout());
          add(vp ,BorderLayout.EAST,1);//3rd argument is index
          setVisible(true);
          repaint();
          revalidate();
        
        
       
        

        
        
    }//GEN-LAST:event_firstAvalJBtnActionPerformed

    private void searchFinalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFinalJButtonActionPerformed
        // TODO add your handling code here:
        
       cc.flushSearchCatalog();
       String check=null;
        
       for (Enumeration<AbstractButton> buttons = searchButtonGroup.getElements(); buttons.hasMoreElements();) {
       AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                check= button.getText();
            }
            
        }
              
        if(searchTxtField.getText().equals("")){
            
                      ViewSearchJPanelFinal vp= new ViewSearchJPanelFinal(cc);
        
       //  newPanel obj = new newPanel ();
          setLayout(new BorderLayout());
          add(vp ,BorderLayout.EAST,1);//3rd argument is index
          setVisible(true);
          repaint();
          revalidate();
            
            JOptionPane.showMessageDialog(null, "Please enter a text to search.");
            
     
          
          
            
        }
        else{

        cc.searchList(searchTxtField.getText(), check);
        
        if(showAvalToggleBtn.isSelected()){

        ListIterator<Car> iter=cc.getCarSearchCatalogue().listIterator();
           while(iter.hasNext()){
               if(iter.next().getIsAvailable()==false){
                   iter.remove();
               }
           }
           
           
        }
        
        
         ViewSearchJPanelFinal vp= new ViewSearchJPanelFinal(cc);
        
       //  newPanel obj = new newPanel ();
          setLayout(new BorderLayout());
          add(vp ,BorderLayout.EAST,1);//3rd argument is index
          setVisible(true);
          repaint();
          revalidate();
          
        }

    }//GEN-LAST:event_searchFinalJButtonActionPerformed

    private void ManufacturerJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManufacturerJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManufacturerJRadioButtonActionPerformed

    private void showAvalToggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAvalToggleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showAvalToggleBtnActionPerformed

    private void expMainCertJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expMainCertJButtonActionPerformed
        // TODO add your handling code here:
        
         cc.flushSearchCatalog();
                
         String serial="Expired";
                
         cc.searchList(serial, "Certificate");
         ViewSearchJPanelFinal vp= new ViewSearchJPanelFinal(cc);

          setLayout(new BorderLayout());
          add(vp ,BorderLayout.EAST,1);//3rd argument is index
          setVisible(true);
          repaint();
          revalidate();
        
        
        
        
    }//GEN-LAST:event_expMainCertJButtonActionPerformed

    private void avaWithSeatsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaWithSeatsJBtnActionPerformed
        // TODO add your handling code here:
        cc.flushSearchCatalog();
        
        if(initialSeatTextField.getText().equals("") || finalSeatTextField.getText().equals(""))
        {
            ViewSearchJPanelFinal vp= new ViewSearchJPanelFinal(cc);

          setLayout(new BorderLayout());
          add(vp ,BorderLayout.EAST,1);//3rd argument is index
          setVisible(true);
          repaint();
          revalidate();
            JOptionPane.showMessageDialog(null, "Please select valid number of seats(1-8).");
                      
        }
        else{
        
        try{
        int start= Integer.parseInt(initialSeatTextField.getText());
        int end= Integer.parseInt(finalSeatTextField.getText());
        cc.searchCarBetweenSeatNumbers(start,end);
        
             ViewSearchJPanelFinal vp= new ViewSearchJPanelFinal(cc);

          setLayout(new BorderLayout());
          add(vp ,BorderLayout.EAST,1);//3rd argument is index
          setVisible(true);
          repaint();
          revalidate();
        }catch(NumberFormatException E){
          ViewSearchJPanelFinal vp= new ViewSearchJPanelFinal(cc);

          setLayout(new BorderLayout());
          add(vp ,BorderLayout.EAST,1);//3rd argument is index
          setVisible(true);
          repaint();
          revalidate();
             JOptionPane.showMessageDialog(null, "Please enter numeric values only.");
      
        }
        
        
      
        
        }    
        
    }//GEN-LAST:event_avaWithSeatsJBtnActionPerformed

    private void ourCarManJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ourCarManJButtonActionPerformed
        // TODO add your handling code here:
        
        cc.flushSearchCatalog();
        
      
        CarManuJPanel vp= new CarManuJPanel(cc);

          setLayout(new BorderLayout());
          add(vp ,BorderLayout.EAST,1);//3rd argument is index
          setVisible(true);
          repaint();
          revalidate(); 
        
    }//GEN-LAST:event_ourCarManJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ManufacturerJRadioButton;
    private javax.swing.JButton avaWithSeatsJBtn;
    private javax.swing.JTextField avalCarsNumJTextField;
    private javax.swing.JRadioButton cityJRadioButton;
    private javax.swing.JButton expMainCertJButton;
    private javax.swing.JTextField finalSeatTextField;
    private javax.swing.JButton firstAvalJBtn;
    private javax.swing.JTextField initialSeatTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton manYearJRadioButton;
    private javax.swing.JRadioButton modNumJRadioButton;
    private javax.swing.JTextField numOfCarsJTextField;
    private javax.swing.JButton ourCarManJButton;
    private javax.swing.ButtonGroup searchButtonGroup;
    private javax.swing.JButton searchFinalJButton;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JToggleButton showAvalToggleBtn;
    private javax.swing.JTextField updatedDateTextField;
    // End of variables declaration//GEN-END:variables
}
