/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Business;
import Business.Person;
import Business.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ankit
 */
public class AddUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddUserAccountJPanel
     */
    private JPanel userProcessContainer;
    private Business business;

    public AddUserAccountJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        populatePerson();
        populateRoles();
    }

    public void populatePerson() {

        for (Person person : business.getEmpDir().getEmpList()) {
            personJComboBox.addItem(person);
        }
    }

    public void populateRoles() {
        roleJComboBox.removeAll();
        // roleJComboBox.addItem(UserAccount.ADMIN_ROLE);
        roleJComboBox.addItem(UserAccount.EMPLOYEE_ROLE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userNameJTxtField = new javax.swing.JTextField();
        pwdJTxtField = new javax.swing.JTextField();
        activeJRadioBtn = new javax.swing.JRadioButton();
        inActiveJRadioBtn = new javax.swing.JRadioButton();
        roleJComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        personJComboBox = new javax.swing.JComboBox<>();
        backJBtn = new javax.swing.JButton();
        createAccJBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Add User Account");

        jLabel2.setText("User Name: ");

        jLabel3.setText("Password: ");

        jLabel4.setText("Is Active? ");

        jLabel5.setText("Person: ");

        activeJRadioBtn.setSelected(true);
        activeJRadioBtn.setText("Yes");
        activeJRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeJRadioBtnActionPerformed(evt);
            }
        });

        inActiveJRadioBtn.setText("No");
        inActiveJRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inActiveJRadioBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Role: ");

        backJBtn.setText("<<Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        createAccJBtn.setText("Create User Account");
        createAccJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(activeJRadioBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(inActiveJRadioBtn))
                                    .addComponent(pwdJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userNameJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(personJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(backJBtn))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createAccJBtn)
                            .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(504, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userNameJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pwdJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(activeJRadioBtn)
                    .addComponent(inActiveJRadioBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(personJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJBtn)
                    .addComponent(createAccJBtn))
                .addContainerGap(217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createAccJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccJBtnActionPerformed
        // TODO add your handling code here:

        String userName = userNameJTxtField.getText().trim();
        String pwd = pwdJTxtField.getText().trim();

        if (userName.equals("") || pwd.equals("")) {
            JOptionPane.showMessageDialog(this, "Invalid user name and password", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        UserAccount ua = business.getUserAccDir().addUserAcc();

        ua.setUserName(userName);
        ua.setPassword(pwd);
        ua.setPerson((Person) personJComboBox.getSelectedItem());
        ua.setRole((String.valueOf(roleJComboBox.getSelectedItem())));

        if (activeJRadioBtn.isSelected()) {
            ua.setIsActive(true);
        } else {
            ua.setIsActive(false);
        }

        JOptionPane.showMessageDialog(this, "Account created successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        userNameJTxtField.setText("");
        pwdJTxtField.setText("");

    }//GEN-LAST:event_createAccJBtnActionPerformed

    private void activeJRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeJRadioBtnActionPerformed
        // TODO add your handling code here:
        if(activeJRadioBtn.isSelected()){
            inActiveJRadioBtn.setSelected(false);
        }
    }//GEN-LAST:event_activeJRadioBtnActionPerformed

    private void inActiveJRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inActiveJRadioBtnActionPerformed
        // TODO add your handling code here:
            if(inActiveJRadioBtn.isSelected()){
            activeJRadioBtn.setSelected(false);
        }
    }//GEN-LAST:event_inActiveJRadioBtnActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
                
        userProcessContainer.remove(this);
        Component[] compArray= userProcessContainer.getComponents();
        Component comp= compArray[compArray.length-1];
        ManageUserAccountsJPanel mejPanel= (ManageUserAccountsJPanel)comp;
        mejPanel.refreshTable();
        
        CardLayout layout= (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeJRadioBtn;
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton createAccJBtn;
    private javax.swing.JRadioButton inActiveJRadioBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<Person> personJComboBox;
    private javax.swing.JTextField pwdJTxtField;
    private javax.swing.JComboBox<String> roleJComboBox;
    private javax.swing.JTextField userNameJTxtField;
    // End of variables declaration//GEN-END:variables
}
