/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageCustomer;

import Business.Customer;
import Business.Flight;
import Business.Ticket;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankit
 */
public class BookingHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookingHistoryJPanel
     */
    private JPanel userProcessContainer;
    private Customer cust;

    BookingHistoryJPanel(JPanel userProcessContainer, Customer cust) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.cust = cust;
        populateTable();
    }

    public void populateTable() {
        int rowCount = customerBookingJTable.getRowCount();

        DefaultTableModel dtm = (DefaultTableModel) customerBookingJTable.getModel();

        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        for (Ticket t : cust.getTickets()) {

            Object[] row = new Object[3];
            row[0] = t;
            row[1] = t.getDate();
            row[2] = t.getSeatNum();

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerBookingJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        viewTicketJBtn = new javax.swing.JButton();
        cancelTicketJButton = new javax.swing.JButton();

        customerBookingJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Name", "Date", "Seats Booked"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerBookingJTable);

        jLabel1.setText("View Booking History");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        viewTicketJBtn.setText("View Details");
        viewTicketJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTicketJBtnActionPerformed(evt);
            }
        });

        cancelTicketJButton.setText("Cancel Ticket");
        cancelTicketJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTicketJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewTicketJBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelTicketJButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addComponent(backButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewTicketJBtn)
                    .addComponent(cancelTicketJButton))
                .addContainerGap(369, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewTicketJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTicketJBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = customerBookingJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;

        }
        Ticket ticket = (Ticket) customerBookingJTable.getValueAt(selectedRow, 0);

        ViewFlightDetailsJPanel panel = new ViewFlightDetailsJPanel(userProcessContainer, ticket);
        userProcessContainer.add("ViewFlightDetailsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_viewTicketJBtnActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);


    }//GEN-LAST:event_backButtonActionPerformed

    private void cancelTicketJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTicketJButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = customerBookingJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;

        }

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to cancel the selected ticket?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            Ticket ticket = (Ticket) customerBookingJTable.getValueAt(selectedRow, 0);

            cust.cancelTicket(ticket);

            JOptionPane.showMessageDialog(null, "Ticket has been successfully cancelled.", "Warning", JOptionPane.WARNING_MESSAGE);

            populateTable();
        }


    }//GEN-LAST:event_cancelTicketJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelTicketJButton;
    private javax.swing.JTable customerBookingJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewTicketJBtn;
    // End of variables declaration//GEN-END:variables
}
