/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageCustomer;

import Business.Customer;
import Business.Flight;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankit
 */
public class FlightAvailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightAvailJPanel
     */
    private JPanel userProcessContainer;
    private ArrayList<Flight> flights;
    private TravelAgency travelAgency;
    private Customer cust;

    FlightAvailJPanel(JPanel userProcessContainer, ArrayList<Flight> flights, TravelAgency travelAgency, Customer cust) {
        initComponents();
        this.flights = flights;
        this.userProcessContainer = userProcessContainer;
        this.travelAgency = travelAgency;
        this.cust=cust;
        populateTable();

    }

    public void populateTable() {

        int rowCount = bookFlightJTable.getRowCount();

        DefaultTableModel dtm = (DefaultTableModel) bookFlightJTable.getModel();

        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        try {
            for (Flight f : flights) {
                
                Object[] row = new Object[7];
                row[0] = f;
                row[1] = f.getAirlinerName();
                row[2] = f.getFromLocation();
                row[3] = f.getToLocation();
                
                row[4] = f.getDate();
                row[5] = f.getTime();
                row[6] = f.getPrice();
                
                dtm.addRow(row);
            }
        } catch (Exception e) {
        }
    }
    
        public void populateTable(ArrayList<Flight> fli) {

        int rowCount = bookFlightJTable.getRowCount();

        DefaultTableModel dtm = (DefaultTableModel) bookFlightJTable.getModel();

        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        try {
            for (Flight f : fli) {
                
                Object[] row = new Object[7];
                row[0] = f;
                row[1] = f.getAirlinerName();
                row[2] = f.getFromLocation();
                row[3] = f.getToLocation();
                
                row[4] = f.getDate();
                row[5] = f.getTime();
                row[6] = f.getPrice();
                
                dtm.addRow(row);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeBtnGroup = new javax.swing.ButtonGroup();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookFlightJTable = new javax.swing.JTable();
        bookJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        morningRadioBtn = new javax.swing.JRadioButton();
        noonRadioBtn = new javax.swing.JRadioButton();
        nightRadioBtn = new javax.swing.JRadioButton();
        noneBtn = new javax.swing.JRadioButton();

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Book Flights");

        bookFlightJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight", "Airlines", "From", "To", "Date", "Time", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookFlightJTable);

        bookJButton.setText("Book");
        bookJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Filter By: ");

        timeBtnGroup.add(morningRadioBtn);
        morningRadioBtn.setText("Morning");
        morningRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morningRadioBtnActionPerformed(evt);
            }
        });

        timeBtnGroup.add(noonRadioBtn);
        noonRadioBtn.setText("After Noon");
        noonRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noonRadioBtnActionPerformed(evt);
            }
        });

        timeBtnGroup.add(nightRadioBtn);
        nightRadioBtn.setText("Night");
        nightRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nightRadioBtnActionPerformed(evt);
            }
        });

        timeBtnGroup.add(noneBtn);
        noneBtn.setSelected(true);
        noneBtn.setText("None");
        noneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noneBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 110, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)
                        .addGap(347, 347, 347)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(bookJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noneBtn)
                        .addGap(8, 8, 8)
                        .addComponent(morningRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noonRadioBtn)
                        .addGap(18, 18, 18)
                        .addComponent(nightRadioBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn)
                    .addComponent(jLabel1))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(morningRadioBtn)
                    .addComponent(noonRadioBtn)
                    .addComponent(nightRadioBtn)
                    .addComponent(noneBtn))
                .addGap(30, 30, 30)
                .addComponent(bookJButton)
                .addContainerGap(249, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookJButtonActionPerformed
        // TODO add your handling code here:
       int selectedRow= bookFlightJTable.getSelectedRow();
         
             if(selectedRow<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
      
             }
         Flight f= (Flight) bookFlightJTable.getValueAt(selectedRow, 0);
         
         FinalBookingJPanel panel= new FinalBookingJPanel(userProcessContainer, f, travelAgency, cust);
         userProcessContainer.add("FinalBookingJPanel", panel);
         CardLayout layout= (CardLayout) userProcessContainer.getLayout();
         layout.next(userProcessContainer);


    }//GEN-LAST:event_bookJButtonActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void morningRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morningRadioBtnActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Flight> filFlight= new ArrayList<>();
        for(Flight f: flights){
            if(f.getTime().equalsIgnoreCase("Morning")){
                filFlight.add(f);
            }
        }
        
        populateTable(filFlight);
    }//GEN-LAST:event_morningRadioBtnActionPerformed

    private void noonRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noonRadioBtnActionPerformed
        // TODO add your handling code here:
          ArrayList<Flight> filFlight= new ArrayList<>();
        for(Flight f: flights){
            if(f.getTime().equalsIgnoreCase("After Noon")){
                filFlight.add(f);
            }
        }
        
        populateTable(filFlight);
    }//GEN-LAST:event_noonRadioBtnActionPerformed

    private void nightRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nightRadioBtnActionPerformed
        // TODO add your handling code here:
          ArrayList<Flight> filFlight= new ArrayList<>();
        for(Flight f: flights){
            if(f.getTime().equalsIgnoreCase("Night")){
                filFlight.add(f);
            }
        }
        
        populateTable(filFlight);
    }//GEN-LAST:event_nightRadioBtnActionPerformed

    private void noneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noneBtnActionPerformed
        // TODO add your handling code here:      
        populateTable();
    }//GEN-LAST:event_noneBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable bookFlightJTable;
    private javax.swing.JButton bookJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton morningRadioBtn;
    private javax.swing.JRadioButton nightRadioBtn;
    private javax.swing.JRadioButton noneBtn;
    private javax.swing.JRadioButton noonRadioBtn;
    private javax.swing.ButtonGroup timeBtnGroup;
    // End of variables declaration//GEN-END:variables
}
