/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageCustomer;

import Business.Customer;
import Business.Flight;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankit
 */
public class ViewCustJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustJPanel
     */
    
    private JPanel userProcessContainer;
    private Customer cust;
    private TravelAgency travelAgency;
  

    ViewCustJPanel(JPanel userProcessContainer, Customer cust,TravelAgency travelAgency ) {
        
                initComponents();
                this.userProcessContainer=userProcessContainer;
                this.cust=cust;
                this.travelAgency = travelAgency;
                custNameTxtField.setText(cust.getName());
                emailIdTxtField.setText(cust.getEmailId());
                contactTxtField.setText(cust.getContactNum());
                addressTxtField.setText(cust.getAddress());
                ageTxtField.setText(Integer.toString(cust.getAge()));
                
                
                updateCustDetailJBtn.setEnabled(true);
                saveBtn.setEnabled(false);
                
                custNameTxtField.setEnabled(false);
                emailIdTxtField.setEnabled(false);
                contactTxtField.setEnabled(false);
                addressTxtField.setEnabled(false);
                ageTxtField.setEnabled(false);
                

    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        custNameTxtField = new javax.swing.JTextField();
        emailIdTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        contactTxtField = new javax.swing.JTextField();
        addressTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bookingHistoryJBtn = new javax.swing.JButton();
        bookFlightJBtn = new javax.swing.JButton();
        updateCustDetailJBtn = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        ageTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setText("Name: ");

        jLabel3.setText("Email Id:");

        jLabel4.setText("Contact Number: ");

        jLabel5.setText("Address: ");

        jLabel1.setText("View Customer");

        bookingHistoryJBtn.setText("View Booking History");
        bookingHistoryJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingHistoryJBtnActionPerformed(evt);
            }
        });

        bookFlightJBtn.setText("Book a New Flight");
        bookFlightJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightJBtnActionPerformed(evt);
            }
        });

        updateCustDetailJBtn.setText("Update");
        updateCustDetailJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustDetailJBtnActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Age:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bookingHistoryJBtn)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(custNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(bookFlightJBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveBtn)
                                .addGap(33, 33, 33)
                                .addComponent(updateCustDetailJBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton)))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(290, 290, 290)
                    .addComponent(jLabel1)
                    .addContainerGap(319, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingHistoryJBtn)
                    .addComponent(bookFlightJBtn))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(custNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateCustDetailJBtn)
                    .addComponent(saveBtn))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jLabel1)
                    .addContainerGap(528, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookFlightJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightJBtnActionPerformed
        // TODO add your handling code here:
        BookFlightJPanel panel= new BookFlightJPanel(userProcessContainer, cust, travelAgency);
        userProcessContainer.add("BookFlightJPanel", panel);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_bookFlightJBtnActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void bookingHistoryJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingHistoryJBtnActionPerformed
        // TODO add your handling code here:
        BookingHistoryJPanel panel= new BookingHistoryJPanel(userProcessContainer, cust);
        userProcessContainer.add("BookingHistoryJPanel", panel);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_bookingHistoryJBtnActionPerformed

    private void updateCustDetailJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustDetailJBtnActionPerformed
        // TODO add your handling code here:
            updateCustDetailJBtn.setEnabled(false);
                saveBtn.setEnabled(true);
                
                custNameTxtField.setEnabled(true);
                emailIdTxtField.setEnabled(true);
                contactTxtField.setEnabled(true);
                addressTxtField.setEnabled(true);
                ageTxtField.setEnabled(true);
    }//GEN-LAST:event_updateCustDetailJBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
                if(addressTxtField.getText().equals("")||ageTxtField.getText().equals("")||contactTxtField.getText().equals("")
          ||emailIdTxtField.getText().equals("")||custNameTxtField.getText().equals("")){ 
            
              JOptionPane.showMessageDialog(null, "None of the fields can be Blank", "Warning", JOptionPane.WARNING_MESSAGE);
         
                return ;
        }
        
   
        try {
           Integer.parseInt(ageTxtField.getText());
        } catch (NumberFormatException numberFormatException) {
                JOptionPane.showMessageDialog(null, "Please enter numeric value for age.", "Warning", JOptionPane.WARNING_MESSAGE);
         
                return ;
        }
        
        cust.setAddress(addressTxtField.getText());
        cust.setAge(Integer.parseInt(ageTxtField.getText()));
        cust.setContactNum(contactTxtField.getText());
        cust.setEmailId(emailIdTxtField.getText());
        cust.setName(custNameTxtField.getText());
        
                        JOptionPane.showMessageDialog(null, "Customer details updated Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);

        
        
            updateCustDetailJBtn.setEnabled(true);
                saveBtn.setEnabled(false);
                
                custNameTxtField.setEnabled(false);
                emailIdTxtField.setEnabled(false);
                contactTxtField.setEnabled(false);
                addressTxtField.setEnabled(false);
                ageTxtField.setEnabled(false);
        
        
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxtField;
    private javax.swing.JTextField ageTxtField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bookFlightJBtn;
    private javax.swing.JButton bookingHistoryJBtn;
    private javax.swing.JTextField contactTxtField;
    private javax.swing.JTextField custNameTxtField;
    private javax.swing.JTextField emailIdTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateCustDetailJBtn;
    // End of variables declaration//GEN-END:variables
}
