/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Business;
import Business.Customer.Customer;
import Business.UserAccount.UserAccount;
import Interface.Supplier.SupplierWorkAreaJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ajaygoel
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private Business business;
    private UserAccount ua;
    private Customer customer;

    public CustomerWorkAreaJPanel(JPanel userProcessContainer, Business business, UserAccount ua) {
        initComponents();
        this.business = business;
        this.userProcessContainer=userProcessContainer;
        this.ua = ua;
        
        for(Customer c: business.getCustomerDirectory().getCustomerDirectory())
            if(c.getUserAccount().equals(ua))
            {
                customer = c;
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ManageAccountsBtn = new javax.swing.JButton();
        ManageOrdersBtn = new javax.swing.JButton();
        ManageProductsBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Customer Work Area");

        ManageAccountsBtn.setText("Manage Accounts");
        ManageAccountsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAccountsBtnActionPerformed(evt);
            }
        });

        ManageOrdersBtn.setText("Manage Orders");
        ManageOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageOrdersBtnActionPerformed(evt);
            }
        });

        ManageProductsBtn.setText("Browse Products");
        ManageProductsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageProductsBtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/comp pic.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ManageAccountsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(ManageAccountsBtn)
                        .addGap(38, 38, 38)
                        .addComponent(ManageOrdersBtn)
                        .addGap(42, 42, 42)
                        .addComponent(ManageProductsBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManageProductsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageProductsBtnActionPerformed
        // TODO add your handling code here:
        
        Interface.Customer.BrowseCustomerProductsJPanel icbwpjp = new Interface.Customer.BrowseCustomerProductsJPanel(userProcessContainer,business, customer);
        userProcessContainer.add("Interface.Customer.BrowseCustomerProductsJPanel",icbwpjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
                    
    }//GEN-LAST:event_ManageProductsBtnActionPerformed

    private void ManageOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageOrdersBtnActionPerformed
        // TODO add your handling code here:
        Interface.Customer.ManageOrdersJPanel icmop = new Interface.Customer.ManageOrdersJPanel(userProcessContainer,business, customer);
        userProcessContainer.add("Interface.Customer.ManageOrdersJPanel",icmop);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageOrdersBtnActionPerformed

    private void ManageAccountsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAccountsBtnActionPerformed
        // TODO add your handling code here:
        Interface.Customer.ManageCustomerAccountJPanel icmcajp = new Interface.Customer.ManageCustomerAccountJPanel(userProcessContainer,ua,customer);
        System.out.println("in customer: "+ ua.getUserName());
        userProcessContainer.add("Interface.Customer.ManageCustomerAccountJPanel",icmcajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageAccountsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageAccountsBtn;
    private javax.swing.JButton ManageOrdersBtn;
    private javax.swing.JButton ManageProductsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
