/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Account;
import Business.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankit
 */
public class ManageAccJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAccJPanel
     */

    private JPanel userProcessContainer;
    private AccountDirectory accDir;

    ManageAccJPanel(JPanel userProcessContainer, AccountDirectory accDir) {
        initComponents();
        this.accDir=accDir;
        this.userProcessContainer= userProcessContainer;
        populateTable();
    }
    public void populateTable(){
        
        DefaultTableModel dtm= (DefaultTableModel) tblAccounts.getModel();
        
        dtm.setRowCount(0);
        
        for(Account acc: accDir.getAccList()){
            Object[] row= new Object [4];
            row[0]= acc;
            row[1]= acc.getRoutingNum();
            row[2]= acc.getAccNum();
            row[3]= acc.getBalance();
            
            dtm.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccounts = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        viewDetailsBtn = new javax.swing.JButton();
        searchTxtField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));

        tblAccounts.setBackground(new java.awt.Color(204, 0, 204));
        tblAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bank Name", "Routing Number", "Account Number", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAccounts);
        if (tblAccounts.getColumnModel().getColumnCount() > 0) {
            tblAccounts.getColumnModel().getColumn(0).setResizable(false);
            tblAccounts.getColumnModel().getColumn(1).setResizable(false);
            tblAccounts.getColumnModel().getColumn(2).setResizable(false);
            tblAccounts.getColumnModel().getColumn(3).setResizable(false);
        }

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search by Account Number: ");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        viewDetailsBtn.setText("View Details");
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });

        searchTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtFieldActionPerformed(evt);
            }
        });

        backBtn.setText("< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn)
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(deleteBtn)
                .addGap(74, 74, 74)
                .addComponent(searchBtn)
                .addGap(33, 33, 33)
                .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewDetailsBtn)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(searchBtn)
                    .addComponent(viewDetailsBtn)
                    .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(302, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
           userProcessContainer.remove(this);
        
        CardLayout layout= (CardLayout) userProcessContainer.getLayout();
        
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedRow= tblAccounts.getSelectedRow();
        
        if(selectedRow>=0){
            
            int dialogButton= JOptionPane.YES_NO_OPTION;
            int dialogResult= JOptionPane.showConfirmDialog(null, "Would you like to delete the selected account", "Warning", dialogButton );
            if(dialogResult==JOptionPane.YES_OPTION){
                Account acc= (Account) tblAccounts.getValueAt(selectedRow, 0);
                        
                        accDir.deleteAccount(acc);
                        
                        populateTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a row first.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow= tblAccounts.getSelectedRow();
        
        if(selectedRow>=0){
            
          
                Account acc= (Account) tblAccounts.getValueAt(selectedRow, 0);
                ViewAccountDetailsJPanel panel= new ViewAccountDetailsJPanel(userProcessContainer,acc);
                userProcessContainer.add("ViewAccountDetailsJPanel", panel);
                CardLayout layout= (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);               
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a row first to view details.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_viewDetailsBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        
        if(searchTxtField.getText().equals("")){
               
       JOptionPane.showMessageDialog(null, "Please enter account number to search.", "Information", JOptionPane.WARNING_MESSAGE);
 
        }
        else{
        
        Account result= accDir.searchAccountNumber(searchTxtField.getText());
        
        if(result==null){
            
       JOptionPane.showMessageDialog(null, "Account number you entered does not exist.", "Information", JOptionPane.WARNING_MESSAGE);

        }
        
        else{
            
              ViewAccountDetailsJPanel panel= new ViewAccountDetailsJPanel(userProcessContainer,result);
                userProcessContainer.add("ViewAccountDetailsJPanel", panel);
                CardLayout layout= (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer); 
            
        }
        searchTxtField.setText("");
        }
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JTable tblAccounts;
    private javax.swing.JButton viewDetailsBtn;
    // End of variables declaration//GEN-END:variables
}
